/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/box.glb --shadows
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/box.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Simbol_01.geometry} material={materials.SimbolMaterial01} scale={[0.45, 0.45, 1.05]} />
      <mesh castShadow receiveShadow geometry={nodes.Simbol_02.geometry} material={materials.SimbolMaterial02} rotation={[Math.PI / 2, 0, 0]} scale={[0.45, 1.05, 0.45]} />
      <mesh castShadow receiveShadow geometry={nodes.Simbol_03.geometry} material={materials.SimbolMaterial03} rotation={[Math.PI / 2, 0, 0]} scale={[0.5, 1.05, 0.5]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.BoxMaterial} />
      <mesh castShadow receiveShadow geometry={nodes.Cube_1.geometry} material={materials.LabelMaterial} />
      <mesh castShadow receiveShadow geometry={nodes.Cube_2.geometry} material={materials.ZipMaterial} />
      <mesh castShadow receiveShadow geometry={nodes.Cube_3.geometry} material={materials.CornerMaterial} />
      <mesh castShadow receiveShadow geometry={nodes.Cube_4.geometry} material={materials.InfoMaterial} />
    </group>
  )
}

useGLTF.preload('/box.glb')
