// CRUD PRODUCTS
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

// export const CREATE_DATA_REQUEST = "CREATE_DATA_REQUEST";
// export const CREATE_DATA_SUCCESS = "CREATE_DATA_SUCCESS";

// export const READ_ALL_DATA_SUCCESS = "READ_ALL_DATA_SUCCESS";
// export const READ_ALL_DATA_FAILURE = "READ_ALL_DATA_FAILURE";

// export const READ_SINGLE_DATA_SUCCESS = "READ_SINGLE_DATA_SUCCESS";
// export const READ_SINGLE_DATA_FAILURE = "READ_SINGLE_DATA_FAILURE";

// export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";
// export const UPDATE_DATA_FAILURE = "UPDATE_DATA_FAILURE";

// export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
// export const DELETE_DATA_FAILURE = "DELETE_DATA_FAILURE";
// export const NO_DATA = "NO_DATA";
