// PRODUCTS
export const GET_PRODUCTS = "GET_PRODUCTS";
export const RESET_PRODUCTS = "RESET_PRODUCTS";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_GENDERS = "GET_GENDERS";
export const GET_GENDER = "GET_GENDER";
export const GET_ALL_SUPPLIERS = "GET_ALL_SUPPLIERS";
export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const GET_SUPPLIER = "GET_SUPPLIER";
export const DELETE_SUPPLIER = "DELETE_SUPPLIER";
export const GET_SIZES = "GET_SIZES";
export const GET_COLORS = "GET_COLORS";

// SALES
export const ADD_PRODUCT_CURRENT_SALE = "ADD_PRODUCT_CURRENT_SALE";
export const UPDATE_PRODUCT_COLOR_CURRENT_SALE =
  "UPDATE_PRODUCT_COLOR_CURRENT_SALE";
export const UPDATE_PRODUCT_SIZE_CURRENT_SALE =
  "UPDATE_PRODUCT_SIZE_CURRENT_SALE";
export const DELETE_PRODUCT_CURRENT_SALE = "DELETE_PRODUCT_CURRENT_SALE";
