/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 pallet.glb --shadows
*/

import React from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/pallet.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor.geometry}
        //  material={materials.FloorMaterial}
        position={[0, -1.96, 0]}
        scale={1.14}
      >
        <meshStandardMaterial color={"#7f4d94"} side={THREE.DoubleSide} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/pallet.glb");
