/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 stckctrl.glb --shadows
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ isLightActive }) {
  const { nodes, materials } = useGLTF("/models/stckctrl.glb");
  return (
    <group dispose={null}>
      <group position={[0, 4, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials.FloorMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={materials.WallMaterial}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Walls.geometry}
        material={materials.WallMaterial}
        position={[0, 0, -2]}
      />
      <group position={[-1.89, 4.14, -0.95]} scale={[0.7, 0.15, 0.7]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          // material={materials.SimbolMaterial03}
        >
          <meshStandardMaterial
            color={"purple"}
            emissive={"purple"}
            emissiveIntensity={isLightActive.triangle ? "2" : "0"}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_1.geometry}
          material={materials.WallMaterial}
        />
      </group>
      <group position={[-0.02, 4.14, -0.95]} scale={[0.7, 0.15, 0.7]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials.WallMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_1.geometry}
          //  material={materials.SimbolMaterial01}
        >
          <meshStandardMaterial
            color={"green"}
            emissive={"green"}
            emissiveIntensity={isLightActive.square ? "2" : "0"}
          />
        </mesh>
      </group>
      <group position={[1.89, 4.14, -0.95]} scale={[0.7, 0.15, 0.7]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          // material={materials.SimbolMaterial02}
        >
          <meshStandardMaterial
            color={"orange"}
            emissive={"orange"}
            emissiveIntensity={isLightActive.circle ? "2" : "0"}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_1.geometry}
          material={materials.WallMaterial}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/stckctrl.glb");
