/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 stckctrl.glb --shadows
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/stckctrl.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 4, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials.FloorMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={materials.WallMaterial}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Walls.geometry}
        material={materials.WallMaterial}
        position={[0, 0, -2]}
      />
      <group position={[-1.89, 4.14, -0.95]} scale={[0.7, 0.15, 0.7]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={materials.SimbolMaterial03}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_1.geometry}
          material={materials.WallMaterial}
        />
      </group>
      <group position={[-0.02, 4.14, -0.95]} scale={[0.7, 0.15, 0.7]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials.WallMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_1.geometry}
          material={materials.SimbolMaterial01}
        />
      </group>
      <group position={[1.89, 4.14, -0.95]} scale={[0.7, 0.15, 0.7]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={materials.SimbolMaterial02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_1.geometry}
          material={materials.WallMaterial}
        />
      </group>
      <group
        position={[4.08, 1.65, -0.59]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.35, 0.07, 0.35]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={materials.SimbolMaterial02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_1.geometry}
          material={materials.WallMaterial}
        />
      </group>
      <group
        position={[0, 1.65, -3.72]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[0.35, 0.07, 0.35]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007.geometry}
          material={materials.SimbolMaterial01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_1.geometry}
          material={materials.WallMaterial}
        />
      </group>
      <group
        position={[-4.12, 1.65, -0.59]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.35, 0.07, 0.35]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008.geometry}
          material={materials.SimbolMaterial03}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_1.geometry}
          material={materials.WallMaterial}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/stckctrl.glb");
