import Head from "next/head";
import { getSession, useSession, signOut } from "next-auth/react";
import Navbar from "@/components/navbar/Nabvar.js";
import { Hero } from "@/components/hero/Hero";

export default function Home() {
  const { data: session } = useSession();

  function handleSignOut() {
    signOut();
  }

  return (
    <>
      <Head>
        <title>stckcrl - home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? (
        <AuthUser session={session} handleSignOut={handleSignOut} />
      ) : (
        <Guest />
      )}
    </>
  );
}

function Guest() {
  return (
    <main className="container mx-auto text-center h-screen max-w-7xl flex flex-col items-center bg-th-background">
      <Navbar />
      <Hero />
    </main>
  );
}

function AuthUser({ session, handleSignOut }) {
  return (
    <main className="container mx-auto text-center py-20">
      <h3 className="text-4xl font-bold">Authorize Homepage</h3>
      <div className="details">
        <h5>Nombre: {session.user.name}</h5>
      </div>
      <div className="flex justify-center">
        <button
          onClick={handleSignOut}
          className="mt-5 px-10 py-1 rounded-sm bg-indigo-500 text-gray-50"
        >
          LogOut
        </button>
      </div>
    </main>
  );
}

export async function getServerSideProps({ req }) {
  const session = await getSession({ req });

  // if (!session) {
  //   return { redirect: { destination: "/login", permanent: false } };
  // }
  return { props: { session } };
}
